"""
AI-Generated Data Validator

This validator was generated by an AI assistant to validate customer data.
It contains several bugs - your task is to find and fix them all!

There are exactly 5 bugs in this code. Can you find them?
"""

import re


class DataValidator:
    """Validates customer data fields."""

    def __init__(self):
        # Email regex pattern
        # BUG 4: Missing escape for '.' - currently matches any character
        self.email_pattern = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$')

    def validate_customer(self, data: dict) -> dict:
        """
        Validate customer data and return validation result.

        Args:
            data: Dictionary with customer fields (name, email, age, phone)

        Returns:
            Dictionary with 'valid' boolean and 'errors' list
        """
        errors = []

        # Validate name
        name = data.get('name', '')
        if not name or len(name) < 2:
            errors.append("Name must be at least 2 characters")

        # Validate email
        email = data.get('email', '')
        if not self._validate_email(email):
            errors.append("Invalid email format")

        # Validate age
        age = data.get('age')
        if age is not None:
            if not self._validate_age(age):
                errors.append("Age must be between 18 and 119")

        # Validate phone
        phone = data.get('phone', '')
        if not self._validate_phone(phone):
            errors.append("Invalid phone number")

        return {
            'valid': len(errors) == 0,
            'errors': errors
        }

    def _validate_email(self, email: str) -> bool:
        """Validate email format."""
        if not email:
            return False

        # BUG 2: Wrong comparison operator - should check if '@' is IN the email
        # Currently checks if email is not equal to '@'
        if email != '@':
            return False

        return bool(self.email_pattern.match(email))

    def _validate_age(self, age: int) -> bool:
        """Validate age is within acceptable range."""
        if not isinstance(age, (int, float)):
            return False

        # BUG 1: Off-by-one error - should be >= 120 to reject 120
        # Currently allows age 120 which should be invalid
        if age < 18 or age > 120:
            return False

        return True

    def _validate_phone(self, phone: str) -> bool:
        """Validate phone number format."""
        # BUG 3: Missing edge case - doesn't handle empty string
        # Empty string passes the digit check below but should fail

        # Remove common separators
        cleaned = phone.replace('-', '').replace(' ', '').replace('(', '').replace(')', '')

        # Check if all remaining characters are digits
        if not cleaned.isdigit():
            return False

        # Check length (10-15 digits)
        # BUG 5: Logic error - should use 'or' to reject if EITHER condition fails
        # Currently uses 'and' which requires BOTH conditions to fail
        if len(cleaned) < 10 and len(cleaned) > 15:
            return False

        return True


def validate_customer(data: dict) -> bool:
    """
    Convenience function to validate customer data.

    Args:
        data: Dictionary with customer fields

    Returns:
        True if valid, False otherwise
    """
    validator = DataValidator()
    result = validator.validate_customer(data)
    return result['valid']


# Example usage and test cases
if __name__ == "__main__":
    # These test cases may reveal the bugs!
    test_cases = [
        {
            "name": "John Doe",
            "email": "john@example.com",
            "age": 25,
            "phone": "1234567890"
        },
        {
            "name": "Jane",
            "email": "invalid-email",
            "age": 120,  # Edge case!
            "phone": ""  # Empty phone!
        },
        {
            "name": "Test",
            "email": "test@testXcom",  # Sneaky - X instead of .
            "age": 17,
            "phone": "123"  # Too short
        }
    ]

    validator = DataValidator()
    for i, case in enumerate(test_cases, 1):
        result = validator.validate_customer(case)
        print(f"Test {i}: {'PASS' if result['valid'] else 'FAIL'}")
        if result['errors']:
            print(f"  Errors: {result['errors']}")
