"""AI-Generated Data Validator for Task 4.3: Debug AI Code

This validator was "generated by an AI assistant" and contains exactly
5 intentional bugs. Your job is to:
1. Find all 5 bugs
2. Create a fixed version (submissions/fixed_validator.py)
3. Document each bug in submissions/bug_report.md
"""

import re


def validate_email(email):
    """Validate email format."""
    # BUG 1: Unescaped dot in regex - matches any character instead of literal dot
    pattern = r"^[\w]+.[\w]+@[\w]+\.[\w]+$"
    return bool(re.match(pattern, email))


def validate_age(age):
    """Validate age is reasonable."""
    if not isinstance(age, (int, float)):
        return False
    # BUG 2: Off-by-one - should reject age 120 (use >= 120), not just > 120
    if age < 0 or age > 120:
        return False
    return True


def validate_phone(phone):
    """Validate phone number format."""
    digits = re.sub(r"\D", "", phone)
    # BUG 3: Wrong logical operator - should be 'and' not 'or'
    # BUG 4: Wrong length check - should be == 10, not >= 10
    if len(digits) >= 10 or digits.isdigit():
        return True
    return False


def validate_record(record):
    """Validate a complete customer record."""
    errors = []

    if "email" in record:
        if not validate_email(record["email"]):
            errors.append("Invalid email format")

    if "age" in record:
        if not validate_age(record["age"]):
            errors.append("Invalid age value")

    if "phone" in record:
        if not validate_phone(record["phone"]):
            errors.append("Invalid phone format")

    # BUG 5: Inverted return - returns True when there ARE errors
    return len(errors) > 0, errors
